#ifndef   __SENSOR_EEP_MAP_H__
#define   __SENSOR_EEP_MAP_H__

#ifdef __SENSOR_EEP_MAP_C__
	#define SENSOR_EEP_MAP
#else
	#define SENSOR_EEP_MAP extern
#endif

/* Start abbreviation */
/* End abbreviation */

/* Start Include */
#include "common.h" 
/* End Include */

/* Start Define */
#define SENSOR_EEP_BLK_SIZE						( 64 ) // words
#define SENSOR_EEP_BLK_BASE( addr )				( addr * SENSOR_EEP_BLK_SIZE )		
#define SENSOR_EEP_PREFIX						( 0x0219 )
/* End Define */

/* Start Enum */
enum {
	/* 01 */ SENSOR_EEP_SYS_CRC = 0,
	/* 02 */ SENSOR_EEP_SYS_PREFIX,
	/* 03 */ SENSOR_EEP_SYS_MODBUS_TIMEOUT_TICK_100uS,
	/* 04 */ SENSOR_EEP_SYS_LOG_MODE,
	/* 05 */ SENSOR_EEP_SYS_RES_05,
	/* 06 */ SENSOR_EEP_SYS_RES_06,
	/* 07 */ SENSOR_EEP_SYS_MODBUS_ADDRESS,
	/* 08 */ SENSOR_EEP_SYS_RES_08,
	/* 09 */ SENSOR_EEP_SYS_RES_09,
	/* 10 */ SENSOR_EEP_SYS_RES_10,
	/* 11 */ SENSOR_EEP_SYS_RES_11,
	/* 12 */ SENSOR_EEP_SYS_RES_12,
	/* 13 */ SENSOR_EEP_SYS_RES_13,
	/* 14 */ SENSOR_EEP_SYS_RES_14,
	/* 15 */ SENSOR_EEP_SYS_RES_15,
	/* 16 */ SENSOR_EEP_SYS_RES_16,
	/* 17 */ SENSOR_EEP_SYS_RES_17,
	/* 18 */ SENSOR_EEP_SYS_RES_18,
	/* 19 */ SENSOR_EEP_SYS_ADC_BUF_SIZE,
	/* 20 */ SENSOR_EEP_SYS_SENSING_PERIOD,
	/* 21 */ SENSOR_EEP_SYS_RES_21,
	/* 22 */ SENSOR_EEP_SYS_RES_22,
	/* 23 */ SENSOR_EEP_SYS_RES_23,
	/* 24 */ SENSOR_EEP_SYS_RES_24,
	/* 25 */ SENSOR_EEP_SYS_RES_25,
	/* 26 */ SENSOR_EEP_SYS_RES_26,
	/* 27 */ SENSOR_EEP_SYS_AMP_CAL_RUN_FLAG,
	/* 28 */ SENSOR_EEP_SYS_RES_28,
	/* 29 */ SENSOR_EEP_SYS_RES_29,
	/* 30 */ SENSOR_EEP_SYS_RES_30,
	/* 31 */ SENSOR_EEP_SYS_RES_31,
	/* 32 */ SENSOR_EEP_SYS_RES_32,
	/* 33 */ SENSOR_EEP_SYS_CTG_DAC_RESET_CNT,
	/* 34 */ SENSOR_EEP_SYS_RES_34,
	/* 35 */ SENSOR_EEP_SYS_RES_35,
	/* 36 */ SENSOR_EEP_SYS_RES_36,
	/* 37 */ SENSOR_EEP_SYS_RES_37,
	/* 38 */ SENSOR_EEP_SYS_CTG_SEN_TYPE_0,
	/* 39 */ SENSOR_EEP_SYS_CTG_SEN_TYPE_1,
	/* 40 */ SENSOR_EEP_SYS_CTG_CONF_NO_0,
	/* 41 */ SENSOR_EEP_SYS_CTG_CONF_NO_1,
	/* 42 */ SENSOR_EEP_SYS_CVT_CONF_NO,
	/* 43 */ SENSOR_EEP_SYS_RES_43,
	/* 44 */ SENSOR_EEP_SYS_RES_44,
	/* 45 */ SENSOR_EEP_SYS_RES_45,
	/* 46 */ SENSOR_EEP_SYS_RES_46,
	/* 47 */ SENSOR_EEP_SYS_RES_47,
	/* 48 */ SENSOR_EEP_SYS_RES_48,
	/* 49 */ SENSOR_EEP_SYS_RES_49,
	/* 50 */ SENSOR_EEP_SYS_RES_50,
	/* 51 */ SENSOR_EEP_SYS_RES_51,
	/* 52 */ SENSOR_EEP_SYS_RES_52,
	/* 53 */ SENSOR_EEP_SYS_RES_53,
	/* 54 */ SENSOR_EEP_SYS_RES_54,
	/* 55 */ SENSOR_EEP_SYS_RES_55,
	/* 56 */ SENSOR_EEP_SYS_RES_56,
	/* 57 */ SENSOR_EEP_SYS_RES_57,
	/* 58 */ SENSOR_EEP_SYS_RES_58,
	/* 59 */ SENSOR_EEP_SYS_RES_59,
	/* 60 */ SENSOR_EEP_SYS_RES_60,
	/* 61 */ SENSOR_EEP_SYS_RES_61,
	/* 62 */ SENSOR_EEP_SYS_RES_62,
	/* 63 */ SENSOR_EEP_SYS_RES_63,
	/* 64 */ SENSOR_EEP_SYS_RES_64
};

enum {
	/* 01 */ SENSOR_EEP_CHn_PREFIX,
	/* 02 */ SENSOR_EEP_CHn_PTM_mOFFS_TIA_0,
	/* 03 */ SENSOR_EEP_CHn_PTM_mGAIN_TIA_1,
	/* 04 */ SENSOR_EEP_CHn_AMP_CAL_TARGET_mV_OFFS,
	/* 05 */ SENSOR_EEP_CHn_AMP_CAL_TARGET_mV_GAIN,
	/* 06 */ SENSOR_EEP_CHn_VBIAS,
	/* 07 */ SENSOR_EEP_CHn_STABLE_HOLD_TIME_SEC,
	/* 08 */ SENSOR_EEP_CHn_mZERO_L,
	/* 09 */ SENSOR_EEP_CHn_mZERO_H,
	/* 10 */ SENSOR_EEP_CHn_mZERO_TEMP_L,
	/* 11 */ SENSOR_EEP_CHn_mZERO_TEMP_H,
	/* 12 */ SENSOR_EEP_CHn_mSPAN_L,
	/* 13 */ SENSOR_EEP_CHn_mSPAN_H,
	/* 14 */ SENSOR_EEP_CHn_mSPAN_TEMP_L,
	/* 15 */ SENSOR_EEP_CHn_mSPAN_TEMP_H,
	/* 16 */ SENSOR_EEP_CHn_SPAN_GAS,
	/* 17 */ SENSOR_EEP_CHn_bZERO_L,
	/* 18 */ SENSOR_EEP_CHn_bZERO_H,
	/* 19 */ SENSOR_EEP_CHn_bZERO_TEMP_L,
	/* 20 */ SENSOR_EEP_CHn_bZERO_TEMP_H,
	/* 21 */ SENSOR_EEP_CHn_bSPAN_L,
	/* 22 */ SENSOR_EEP_CHn_bSPAN_H,
	/* 23 */ SENSOR_EEP_CHn_bSPAN_TEMP_L,
	/* 24 */ SENSOR_EEP_CHn_bSPAN_TEMP_H,
	/* 25 */ SENSOR_EEP_CHn_RES_25,
	/* 26 */ SENSOR_EEP_CHn_GAS_NAME_0,
	/* 27 */ SENSOR_EEP_CHn_GAS_NAME_1,
	/* 28 */ SENSOR_EEP_CHn_GAS_NAME_2,
	/* 29 */ SENSOR_EEP_CHn_GAS_NAME_3,
	/* 30 */ SENSOR_EEP_CHn_GAS_NAME_4,
	/* 31 */ SENSOR_EEP_CHn_GAS_NAME_5,
	/* 32 */ SENSOR_EEP_CHn_RES_32,
	/* 33 */ SENSOR_EEP_CHn_bZERO_USE,
	/* 34 */ SENSOR_EEP_CHn_bZERO_PERCENTAGE_x10,
	/* 35 */ SENSOR_EEP_CHn_bZERO_SEC,
	/* 36 */ SENSOR_EEP_CHn_bZERO_COUNT,
	/* 37 */ SENSOR_EEP_CHn_METHOD,
	/* 38 */ SENSOR_EEP_CHn_SEN_NO,
	/* 39 */ SENSOR_EEP_CHn_GAS_NO,
	/* 40 */ SENSOR_EEP_CHn_DP,
	/* 41 */ SENSOR_EEP_CHn_HIGH_SCALE,
	/* 42 */ SENSOR_EEP_CHn_UNIT,
	/* 43 */ SENSOR_EEP_CHn_MAINTENANCE_GAS,
	/* 44 */ SENSOR_EEP_CHn_CROSS_SENS_SCALE_x100,
	/* 45 */ SENSOR_EEP_CHn_ZERO_SKIP_PERCENTAGE_x10,
	/* 46 */ SENSOR_EEP_CHn_SPAN_SKIP_PERCENTAGE_x10,
	/* 47 */ SENSOR_EEP_CHn_OUT_DELAY_PERCENTAGE_x10,
	/* 48 */ SENSOR_EEP_CHn_OUT_DELAY_SEC,
	/* 49 */ SENSOR_EEP_CHn_ALARM_UNDER_CHECK,
	/* 50 */ SENSOR_EEP_CHn_ALARM_1ST_LATCH,
	/* 51 */ SENSOR_EEP_CHn_ALARM_1ST_INCREASE_TYPE,
	/* 52 */ SENSOR_EEP_CHn_ALARM_1ST_LEVEL,
	/* 53 */ SENSOR_EEP_CHn_ALARM_1ST_DEAD_BAND,
	/* 54 */ SENSOR_EEP_CHn_ALARM_1ST_DELAY_SEC,
	/* 55 */ SENSOR_EEP_CHn_ALARM_2ND_LATCH,
	/* 56 */ SENSOR_EEP_CHn_ALARM_2ND_INCREASE_TYPE,
	/* 57 */ SENSOR_EEP_CHn_ALARM_2ND_LEVEL,
	/* 58 */ SENSOR_EEP_CHn_ALARM_2ND_DEAD_BAND,
	/* 59 */ SENSOR_EEP_CHn_ALARM_2ND_DELAY_SEC,
	/* 60 */ SENSOR_EEP_CHn_RES_60,
	/* 61 */ SENSOR_EEP_CHn_RES_61,
	/* 62 */ SENSOR_EEP_CHn_RES_62,
	/* 63 */ SENSOR_EEP_CHn_RES_63,
	/* 64 */ SENSOR_EEP_CHn_RES_64
};
/* End Enum */

/* Start Struct */
/* End Struct */

/* Start Function */
/* End Function */

/* Start Variable */
extern const U16	SENSOR_EEP_CT_CHn_DEFAULT[SENSOR_EEP_BLK_SIZE];
extern const U16	SENSOR_EEP_IR_CHn_DEFAULT[SENSOR_EEP_BLK_SIZE];
/* End Variable */


#endif // __SENSOR_EEP_MAP_H__


